[package]
name = "osm2parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
osm = { git = "https://github.com/ximonsson/osm-rs.git" }
parquet = { version = "39.0" }

[[bin]]
name = "osm2parquet"
