[package]
name = "osm2parquet"
version = "0.1.0"
edition = "2021"

[dependencies]
osm = { git = "https://github.com/ximonsson/osm-rs.git" }
polars = { version = "0.28", features = ["parquet"] }

[[bin]]
name = "osm2parquet"
